---
- name: sample book
  hosts: all
  become: true
  tasks:

          - name: install pip3
            apt: name=python3-pip state=present

          - name: install docker-py
            pip: name=docker-py

          - name: Adding Docker Key
            apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present

          - name: Docker Repository
            apt_repository:
                    repo: deb https://download.docker.com/linux/ubuntu bionic stable
                    state: present

          - name: Install docker-ce
            apt: update_cache=yes name=docker-ce state=latest

          - name: Download Nginx
            apt: name=nginx state=latest

          - name: start nginx
            service:
                    name: nginx
                    state: started

          - name: Pull and Run Docker Image
            command: docker run -d --name royalsuites-app  -p 8000:8000 swastikb/royalsuites-app:latest
